version: "2"

services:
    php-fpm:
        image: lordius/alpine-php_fpm
        links:
            - mailhog            
            - mysql            
            - memcached
        depends_on:
            - mailhog
            - mysql
            - memcached
        volumes:
            - ./crontasks.txt:/home/crontasks.txt
            - ./htdocs:/var/www/localhost/htdocs
        environment:
            DRUSH_VERSION: 8.x
            PHP_SHOW_ERRORS: 1
            CRONTAB_ENABLED: 0
            PHP_FPM_PORT: 7000
            PHP_SENDMAIL_PATH: /usr/sbin/sendmail -i -t
            PHP_SENDMAIL_HOST: mailhog
            PHP_SENDMAIL_PORT: 1025
            PHP_XDEBUG_ENABLED: 1
            PHP_XDEBUG_PORT: 8010
            PHP_MAX_EXECUTION_TIME: 250
            PHP_UPLOAD_MAX_FILESIZE: 1024M
            PHP_POST_MAX_SIZE: 756M
            PHP_ALLOW_URL_FOPEN: "On"
            PHP_MEMORY_LIMIT: 1024M
        networks:
            - internal
        extra_hosts:
            - "local.dockerhost:172.55.0.2"
            - "adminer.dockerhost:172.55.0.5"
            - "mailhog.dockerhost:172.55.0.6"
            - "mysql.dockerhost:172.55.0.3"
            - "memcached.dockerhost:172.55.0.4"
    apache2_mpm:
        image: lordius/alpine-apache
        links:
            - php-fpm
        depends_on:
            - php-fpm
        volumes_from:
            - php-fpm
        environment:
            DOCUMENT_ROOT: /var/www/localhost/htdocs
            PROXY_PASS: fcgi://php-fpm:7000/var/www/localhost/htdocs
            APACHE_LISTEN_PORT: 80
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.2
    mailhog:
        image: lordius/alpine-mailhog
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.6

# Database images.

    mysql:
        image: mariadb:10.0
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_USER: test
            MYSQL_PASSWORD: toor
            MYSQL_DATABASE: test
        # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.3

# DB managers.

    adminer:
        image: adminer
        links:
            - mysql
        depends_on:
            - mysql
        restart: always
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.5

# Cache-memory images.

    memcached:
        image: memcached
        networks:
            internal:
            shared:
                ipv4_address: 172.55.0.4

networks:
    internal:
        driver_opts:
           internal: "true"
        driver: bridge      
    shared:
        driver_opts:
          enable_ipv6: "true"
        driver: bridge
        ipam:
           config:
              - subnet: 172.55.0.0/16
                gateway: 172.55.0.1

volumes:
    db_data: